# Generated by Django 2.1 on 2020-01-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
