# Generated by Django 2.1 on 2020-01-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200108_2320'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrequests',
            table='ui_table_details',
        ),
    ]
