# Generated by Django 2.1 on 2020-03-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200113_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequests',
            name='date',
        ),
    ]
