# Generated by Django 2.1 on 2020-03-02 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_userrequests_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
